/// Flutter icons LifeWish
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LifeWish
///      fonts:
///       - asset: fonts/LifeWish.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LifeWish {
  LifeWish._();

  static const _kFontFam = 'LifeWish';
  static const _kFontPkg = null;

  static const IconData facebook_logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_us = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_abuse = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy_policy = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData licence = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData item_black = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_life_wish = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_setting = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_languaue = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive_life_wish = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calander = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData actionbar_icon = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Logo = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
